name: Deploy to Development

on:
  push:
    branches:
      - development  # o el nombre de tu rama de desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Asegúrate de que este comando construye tu sitio en la carpeta "build" o similar

    - name: Deploy to Development
      run: |
        # Copia los archivos desde la carpeta de construcción (src) a la ubicación deseada
        cp -r src/* /

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Deploy to Development"
        git push origin development  # o el nombre de tu rama de desarrollo
